name: Week 1 Lab CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Check Docker
        run: docker --version

      - name: Check repository files
        run: |
          ls
          ls vote
          ls result
          ls worker

      - name: Build test containers
        run: |
          docker compose -f result/docker-compose.test.yml build